version: "3.8"
services:
    frontend:
        container_name: frontend
        image: aimeeh97/frontend_image
        build: ./frontend
        ports:
        - target: 5000
          published: 5000
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: flask-db

    backend:
        container_name: backend
        image: aimeeh97/backend_image
        build: ./backend
        # ports:
        #     - target: 5000
        #     published: 5000
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: flask-db
   
    
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
        - target: 80
          published: 80
          protocol: tcp
        volumes:
        - type: bind
          source: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf
