- hosts: test
  become: true
  roles:
  - docker
  - python
- hosts: production
  become: true
  roles:
  - docker
  - python
- hosts: jenkins
  become: true
  roles:
  - docker
  - jenkins
  - python