variable "net_id" {}
variable "net_id_test" {}
variable "net_id_jenkins" {}
variable "ami_id" {}
variable "instance_type" {}
variable "av_zone" {}
variable "key_name" {}
#variable "user_data" {}
variable "subnet_group_name" {}
variable "sec_group_id_sql" {}